spring:
  application:
    name: servicio-notificaciones
  datasource:
    url: ${URL_BD_NOTIFICACIONES}
    username: ${USUARIO_NOTIFICACIONES}
    password: ${CONTRASENA_NOTIFICACIONES}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method