spring:
  application:
    name: servicio-notificaciones
  datasource:
    url: ${URL_BD}
    username: ${USUARIO_NOTIFICACIONES}
    password: ${CONTRASENA_NOTIFICACIONES}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "health,info"