spring:
  application:
    name: servicio-autenticacion
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${URL_BD_AUTH}
    username: ${USUARIO_AUTH}
    password: ${CONTRASENA_AUTH}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method