spring:
  application:
    name: servicio-inventario
  datasource:
    url: ${URL_BD_INVENTARIO}
    username: ${USUARIO_INVENTARIO}
    password: ${CONTRASENA_INVENTARIO}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${URL_EUREKA}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "health,info"